### ISSUE TITLE
Crash on long play game.

### ISSUE THREAD

**Issue by DJOxid** [fluxroot/flux#80]
java.lang.ArrayIndexOutOfBoundsException: length=64; index=-1
com.fluxchess.board.Hex88Board.addPosition(Hex88Board.java:1663)
com.fluxchess.board.Hex88Board.move(Hex88Board.java:405)
com.fluxchess.board.Hex88Board.undoMoveNormal(Hex88Board.java:1315)
com.fluxchess.board.Hex88Board.undoMove(Hex88Board.java:1182)
com.fluxchess.Search.quiescent(Search.java:1487)
com.fluxchess.Search.alphaBeta(Search.java:926)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1264)
com.fluxchess.Search.alphaBeta(Search.java:1269)
com.fluxchess.Search.alphaBetaRoot(Search.java:756)
com.fluxchess.Search.getBestMove(Search.java:512)
com.fluxchess.Search.run(Search.java:191)
java.lang.Thread.run(Thread.java:841)

I'm create chess game with flux engine at android phone.
Sometimes it's crashes after engine receives command for search best move.

**Comment by fanticqq** [comment]
Hello, there is a similar problem in my android app.

03-31 12:42:35.318: E/AndroidRuntime(15693): FATAL EXCEPTION: Thread-1497
03-31 12:42:35.318: E/AndroidRuntime(15693): Process: com.me.example.chess, PID: 15693
03-31 12:42:35.318: E/AndroidRuntime(15693): java.lang.IllegalArgumentException
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.table.RepetitionTable.remove(RepetitionTable.java:75)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.board.Hex88Board.undoMove(Hex88Board.java:1171)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1267)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1242)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1242)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1242)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1242)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1242)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1242)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBeta(Search.java:1247)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.alphaBetaRoot(Search.java:734)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.getBestMove(Search.java:490)
03-31 12:42:35.318: E/AndroidRuntime(15693): at com.fluxchess.flux.Search.run(Search.java:169)
03-31 12:42:35.318: E/AndroidRuntime(15693): at java.lang.Thread.run(Thread.java:818)
